name = "upload-web-worker"
compatibility_date = "2023-02-02"
main = "src/index.js"
compatibility_date = "2023-01-26"
account_id = 'SET YOUR ACCOUNT ID HERE'
workers_dev = true

[dev]
port = 4000

[[r2_buckets]]
binding = 'DOWNLOAD_STORAGE_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'downloads-storage'
# preview_bucket_name = 'downloads-storage'
